#!/bin/bash
echo -n " variables   [" 

export CLICOLOR=1                                    && echo -n "."
export LSCOLORS=dxFxCxDxBxegedabagacad
export HISTCONTROL="ignoredups"                      && echo -n "."
export HISTSIZE="2000"                               && echo -n "."

export EDITOR="vim"                                  && echo -n "."
export PAGER=less                                    && echo -n "."
export LESS="-X -M -E -R"                            && echo -n "."
export LESSOPEN="| $HOME/bin/lesspipe.sh %s"         && echo -n "."
export LS_OPTIONS="--color=yes  -F -b -T 0"          && echo -n "."
export BLOCKSIZE=K                                   && echo -n "."
export PARINIT='w72jrT4bgqR B=.,?_A_a Q=_s>|'        && echo -n "."
export LC_CTYPE=en_US.UTF-8                          && echo -n "."
export VIM_APP_DIR=/Applications/Other               && echo -n "."
export GREP_OPTIONS='--color=auto'                   && echo -n "."
export GREP_COLOR='1;33'                             && echo -n "."

#export BASH_COMPLETION=~/.bash/bash_completion/bash_completion     && echo -n "."
#export BASH_COMPLETION_DIR=~/.bash/bash_completion.d     && echo -n "."

export PATH=~/bin                                     && echo -n "."
export PATH=$PATH:~/.gem/ruby/1.8/bin                 && echo -n "."
export PATH=$PATH:/usr/local/bin                      && echo -n "."
export PATH=$PATH:/usr/local/sbin                     && echo -n "."
export PATH=$PATH:/usr/local/mysql/bin                && echo -n "."
export PATH=$PATH:/opt/local/bin                      && echo -n "."
export PATH=$PATH:/opt/local/sbin                     && echo -n "."
export PATH=$PATH:/usr/bin                            && echo -n "."
export PATH=$PATH:/usr/sbin                           && echo -n "."
export PATH=$PATH:/bin                                && echo -n "."
export PATH=$PATH:/sbin                               && echo -n "."

export MANPATH=/opt/local/share/man:$MANPATH          && echo -n "."
export MANPATH=/usr/local/man:$MANPATH                && echo -n "."

export RUBY_HEAP_MIN_SLOTS=2000000;
export RUBY_HEAP_SLOTS_INCREMENT=500000;
export RUBY_HEAP_SLOTS_GROWTH_FACTOR=1;
export RUBY_GC_MALLOC_LIMIT=75000000;

[ $TERM = "screen" ] && export TERM=xterm           && echo -n "."

complete -C ~/.bash/mycompletions/rake.rb -o default rake

source ~/.bash/colors

echo "]"
